name: gs-view
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  - pytorch=2.3
  - cudatoolkit=11.8
  - pytorch-cuda=11.8

  - click=8.1
  - glfw=3.4
  - imageio-ffmpeg=0.5
  - imageio=2.34
  - munch=4.0
  - numpy<2
  - opencv=4.9
  - pandas=2.2
  - pillow=10.3
  - plyfile=1.0
  - pydantic=2.8
  - pyopengl=3.1
  - requests=2.31
  - scipy=1.13
  - tqdm=4.66

  - pip:
    - gaussian-splatting/submodules/diff-gaussian-rasterization
    - imgui_bundle==1.5.2
    - imgui==2.0.0
    - scikit-image==0.24
    - imagecodecs[all]==2024.6.1
    - pynvml
    - GPUtil
    - ninja
