name: gs-view
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.10
  - pip
  - pytorch
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - tqdm
  - click
  - pillow
  - torchaudio
  - torchvision
  - requests
  - tqdm
  - matplotlib
  - imageio
  - scikit-learn
  - kornia
  - opencv
  - scipy
  - pandas
  - trimesh
  - pip:
    - imgui==2.0.0
    - imgui_bundle
    - glfw
    - pyopengl
    - imageio-ffmpeg
    - pyspng
    - psutil
    - mrcfile
    - tensorboard
    - gaussian-splatting/submodules/diff-gaussian-rasterization
    - gaussian-splatting/submodules/simple-knn
    - wandb
    - smplx
    - chumpy==0.70
    - numpy==1.23.1
    - pytorch_msssim
    - imagecodecs[all]